services:
  - type: web
    name: catting-website
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    routes:
      - type: web
        plan: free
    github:
      branch: main
      deploy: true